#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "arm-none-linux-gnueabi-gcc -O"
  #define PLATFORM "dist"
  #define DATE "Mon Oct 30 20:14:18 PDT 2017"
#endif
